# Generated by Django 5.2.17 on 2026-09-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Aviso"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Crítico"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("suppressed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_key", models.CharField(max_length=64, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "cron",
                    models.CharField(
                        help_text="5-field cron expression, UTC.", max_length=64
                    ),
                ),
                ("max_per_run", models.IntegerField(default=10)),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "next_run_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "programación",
                "verbose_name_plural": "programaciones",
                "ordering": ["pipeline_key"],
            },
        ),
        migrations.CreateModel(
            name="JobQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_key", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "priority",
                    models.SmallIntegerField(
                        db_index=True, default=50, help_text="Lower runs sooner."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "En cola"),
                            ("RUNNING", "Ejecutando"),
                            ("DONE", "Completado"),
                            ("FAILED", "Fallido"),
                            ("DEFERRED", "Aplazado"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("available_at", models.DateTimeField(db_index=True)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("max_attempts", models.SmallIntegerField(default=3)),
                ("locked_by", models.CharField(blank=True, max_length=64)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dedupe_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "trabajo en cola",
                "verbose_name_plural": "trabajos en cola",
                "ordering": ["priority", "available_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority", "available_at"],
                        name="job_claim_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["QUEUED", "RUNNING", "DEFERRED"]),
                            models.Q(("dedupe_key", ""), _negated=True),
                        ),
                        fields=("dedupe_key",),
                        name="uniq_jobqueue_active_dedupe_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_key", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Ejecutando"),
                            ("SUCCESS", "Correcto"),
                            ("FAILED", "Fallido"),
                            ("SKIPPED", "Omitido"),
                        ],
                        db_index=True,
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("skip_reason", models.CharField(blank=True, max_length=128)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("items_in", models.IntegerField(default=0)),
                ("items_created", models.IntegerField(default=0)),
                ("items_updated", models.IntegerField(default=0)),
                ("items_failed", models.IntegerField(default=0)),
                ("keepa_tokens_used", models.IntegerField(default=0)),
                (
                    "llm_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("error", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="pipelines.jobqueue",
                    ),
                ),
            ],
            options={
                "verbose_name": "ejecución",
                "verbose_name_plural": "ejecuciones",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("purpose", models.CharField(db_index=True, max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_calls",
                        to="pipelines.pipelinerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "llamada LLM",
                "verbose_name_plural": "llamadas LLM",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="KeepaTokenLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("endpoint", models.CharField(max_length=32)),
                ("tokens_consumed", models.IntegerField(default=0)),
                ("tokens_left", models.IntegerField(default=0)),
                ("refill_in_ms", models.IntegerField(blank=True, null=True)),
                ("refill_rate", models.IntegerField(blank=True, null=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keepa_calls",
                        to="pipelines.pipelinerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de tokens Keepa",
                "verbose_name_plural": "movimientos de tokens Keepa",
                "ordering": ["-at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStepRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Ejecutando"),
                            ("SUCCESS", "Correcto"),
                            ("FAILED", "Fallido"),
                            ("SKIPPED", "Omitido"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="pipelines.pipelinerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "paso de ejecución",
                "verbose_name_plural": "pasos de ejecución",
                "ordering": ["started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["pipeline_key", "-started_at"], name="run_pipeline_recent_idx"
            ),
        ),
    ]
