# Generated by Django 5.2.17 on 2026-09-13 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipelines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("at", models.DateTimeField(db_index=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("jobs_processed", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pipelines.jobqueue",
                    ),
                ),
            ],
            options={
                "verbose_name": "latido del worker",
                "verbose_name_plural": "latidos del worker",
                "ordering": ["name"],
            },
        ),
    ]
