# Generated by Django 5.2.17 on 2026-09-13 15:38

import django.db.models.deletion
import pgvector.django.halfvec
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("w_semantic", models.FloatField(default=0.45)),
                ("w_lexical", models.FloatField(default=0.15)),
                ("w_quality", models.FloatField(default=0.2)),
                ("w_ctr", models.FloatField(default=0.1)),
                ("w_freshness", models.FloatField(default=0.1)),
                (
                    "topic_match_threshold",
                    models.FloatField(
                        default=0.9,
                        help_text="Cosine similarity above which a search redirects to a topic page.",
                    ),
                ),
                ("min_facet_similarity", models.FloatField(default=0.55)),
                ("candidate_pool_size", models.IntegerField(default=200)),
                ("results_per_page", models.IntegerField(default=24)),
                ("max_per_brand", models.SmallIntegerField(default=2)),
                ("max_per_category", models.SmallIntegerField(default=3)),
                ("cache_ttl_hours", models.IntegerField(default=24)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "configuración de ranking",
                "verbose_name_plural": "configuración de ranking",
            },
        ),
        migrations.CreateModel(
            name="SearchResultCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_hash", models.CharField(max_length=32, unique=True)),
                (
                    "payload",
                    models.JSONField(help_text="Ordered product ids plus metadata."),
                ),
                ("hits", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "caché de resultados",
                "verbose_name_plural": "caché de resultados",
            },
        ),
        migrations.CreateModel(
            name="QueryDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized", models.CharField(db_index=True, max_length=255)),
                ("day", models.DateField(db_index=True)),
                ("hits", models.IntegerField(default=0)),
                ("zero_results", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                ("avg_similarity", models.FloatField(blank=True, null=True)),
                (
                    "matched_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="topics.topic",
                    ),
                ),
                (
                    "promoted_topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this demand was turned into a Topic.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "demanda de búsqueda",
                "verbose_name_plural": "demanda de búsqueda",
                "ordering": ["-day", "-hits"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("normalized", "day"),
                        name="uniq_querydemand_normalized_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField()),
                ("normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "query_hash",
                    models.CharField(
                        db_index=True, help_text="md5(normalized+slots)", max_length=32
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("SIMPLE", "Simple"), ("ADVANCED", "Avanzada")],
                        db_index=True,
                        default="SIMPLE",
                        max_length=16,
                    ),
                ),
                ("slots", models.JSONField(blank=True, default=dict)),
                ("match_similarity", models.FloatField(blank=True, null=True)),
                ("result_count", models.IntegerField(default=0)),
                ("is_zero_result", models.BooleanField(db_index=True, default=False)),
                ("served_from_cache", models.BooleanField(default=False)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("referrer_host", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "matched_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta de usuario",
                "verbose_name_plural": "consultas de usuario",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "is_zero_result"],
                        name="userquery_recent_zero_idx",
                    )
                ],
            },
        ),
    ]
