# Generated by Django 5.2.17 on 2026-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_seed_rankingconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingconfig",
            name="price_band_economico_max_cents",
            field=models.IntegerField(
                default=2500,
                help_text="Hasta este importe, ECONOMICO. Por defecto 25 €.",
            ),
        ),
        migrations.AddField(
            model_name="rankingconfig",
            name="price_band_medio_max_cents",
            field=models.IntegerField(
                default=7500,
                help_text="Hasta este importe, MEDIO. Por encima, PREMIUM. Por defecto 75 €.",
            ),
        ),
    ]
