# Generated by Django 5.2.17 on 2026-09-13 15:38

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "title",
                    models.CharField(
                        help_text="H1 of the landing page.", max_length=200
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                (
                    "intro_html",
                    models.TextField(blank=True, help_text="Short, human-reviewed."),
                ),
                (
                    "canonical_text",
                    models.TextField(
                        help_text="Normalised query form used for embedding."
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
                ("embedding_version", models.SmallIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OCCASION", "Ocasión"),
                            ("RECIPIENT", "Para quién"),
                            ("INTEREST", "Afición"),
                            ("BUDGET", "Presupuesto"),
                            ("HYBRID", "Híbrido"),
                        ],
                        default="HYBRID",
                        max_length=16,
                    ),
                ),
                (
                    "occasions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "price_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ECONOMICO", "Económico"),
                            ("MEDIO", "Medio"),
                            ("PREMIUM", "Premium"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("LLM", "LLM"),
                            ("MINED_QUERY", "Demanda de búsqueda"),
                            ("MINED_GSC", "Search Console"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("ACTIVE", "Activo"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        default=50, help_text="Higher runs sooner in pipelines."
                    ),
                ),
                ("linked_count", models.IntegerField(default=0)),
                ("distinct_categories", models.IntegerField(default=0)),
                ("distinct_brands", models.IntegerField(default=0)),
                ("quality_score", models.FloatField(default=0)),
                (
                    "is_indexable",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Computed. Controls robots meta and the sitemap.",
                    ),
                ),
                ("human_reviewed", models.BooleanField(default=False)),
                ("seasonal_start", models.DateField(blank=True, null=True)),
                ("seasonal_end", models.DateField(blank=True, null=True)),
                (
                    "last_curated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_from",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "tema",
                "verbose_name_plural": "temas",
                "ordering": ["-priority", "slug"],
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En curso"),
                            ("DONE", "Completado"),
                            ("FAILED", "Fallido"),
                            ("EXHAUSTED", "Agotado"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("priority", models.SmallIntegerField(default=50)),
                ("run_count", models.IntegerField(default=0)),
                ("products_found", models.IntegerField(default=0)),
                ("keepa_tokens", models.IntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "término de búsqueda",
                "verbose_name_plural": "términos de búsqueda",
            },
        ),
        migrations.CreateModel(
            name="ProductTopicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(db_index=True)),
                ("rank", models.SmallIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AUTO", "Automático"),
                            ("MANUAL", "Manual"),
                            ("PINNED", "Fijado"),
                        ],
                        default="AUTO",
                        max_length=16,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, help_text="Survives recompute."),
                ),
                (
                    "is_excluded",
                    models.BooleanField(default=False, help_text="Survives recompute."),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_links",
                        to="catalog.product",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto en tema",
                "verbose_name_plural": "productos en tema",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="TopicAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("normalized", models.CharField(max_length=255, unique=True)),
                (
                    "embedding",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("MINED_QUERY", "Demanda de búsqueda"),
                            ("LLM", "LLM"),
                        ],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                ("hits", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "alias de tema",
                "verbose_name_plural": "alias de tema",
            },
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["status", "is_indexable"], name="topic_status_indexable_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="topic_embedding_hnsw",
                opclasses=["halfvec_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="searchterm",
            constraint=models.UniqueConstraint(
                fields=("topic", "normalized"), name="uniq_searchterm_topic_normalized"
            ),
        ),
        migrations.AddIndex(
            model_name="producttopiclink",
            index=models.Index(fields=["topic", "rank"], name="link_topic_rank_idx"),
        ),
        migrations.AddConstraint(
            model_name="producttopiclink",
            constraint=models.UniqueConstraint(
                fields=("topic", "product"), name="uniq_producttopiclink_topic_product"
            ),
        ),
        migrations.AddIndex(
            model_name="topicalias",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="alias_embedding_hnsw",
                opclasses=["halfvec_cosine_ops"],
            ),
        ),
    ]
