# Generated by Django 5.2.17 on 2026-09-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_initial"),
        ("search", "0001_initial"),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=255)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("referrer_host", models.CharField(blank=True, max_length=255)),
                ("is_bot", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "visita",
                "verbose_name_plural": "visitas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("SIMPLE_SEARCH", "Búsqueda simple"),
                            ("ADVANCED_SEARCH", "Búsqueda avanzada"),
                            ("TOPIC_PAGE", "Página de tema"),
                            ("HOME", "Home"),
                            ("RELATED", "Relacionados"),
                            ("ARTICLE", "Artículo"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "button",
                    models.CharField(
                        choices=[
                            ("SEE_PRICE", "Ver precio"),
                            ("SEE_REVIEWS", "Ver reseñas"),
                            ("DETAILS", "Ver detalles"),
                            ("IMAGE", "Imagen"),
                            ("TITLE", "Título"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "position",
                    models.SmallIntegerField(
                        blank=True, help_text="Rank in the list.", null=True
                    ),
                ),
                ("page_path", models.CharField(blank=True, max_length=255)),
                ("referrer_host", models.CharField(blank=True, max_length=255)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("ascsubtag", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="click_events",
                        to="catalog.product",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="topics.topic",
                    ),
                ),
                (
                    "user_query",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="search.userquery",
                    ),
                ),
            ],
            options={
                "verbose_name": "clic",
                "verbose_name_plural": "clics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="click_product_recent_idx",
                    ),
                    models.Index(
                        fields=["placement", "button"],
                        name="click_placement_button_idx",
                    ),
                ],
            },
        ),
    ]
