# Generated by Django 5.2.17 on 2026-09-13 15:38

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(db_index=True, max_length=10)),
                (
                    "domain_id",
                    models.SmallIntegerField(
                        default=9, help_text="Keepa domain id. 9 = amazon.es"
                    ),
                ),
                ("title", models.TextField()),
                (
                    "brand",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("model", models.CharField(blank=True, default="", max_length=255)),
                (
                    "parent_asin",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                (
                    "product_group",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "root_category_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "category_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("description_text", models.TextField(blank=True)),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=500),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("review_count", models.IntegerField(blank=True, null=True)),
                ("sales_rank", models.IntegerField(blank=True, null=True)),
                ("is_adult", models.BooleanField(default=False)),
                ("listed_since", models.DateTimeField(blank=True, null=True)),
                (
                    "price_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ECONOMICO", "Económico"),
                            ("MEDIO", "Medio"),
                            ("PREMIUM", "Premium"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("price_band_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sales_rank_pct",
                    models.FloatField(
                        blank=True,
                        help_text="0 = best, 1 = worst within the root category.",
                        null=True,
                    ),
                ),
                ("quality_score", models.FloatField(db_index=True, default=0)),
                ("ctr_score", models.FloatField(default=0)),
                (
                    "variation_group_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="parent_asin when present, otherwise asin. Collapses variations in results.",
                        max_length=16,
                    ),
                ),
                (
                    "keepa_fetched_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("keepa_payload_hash", models.CharField(blank=True, max_length=64)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("availability_note", models.CharField(blank=True, max_length=255)),
                (
                    "is_blocked",
                    models.BooleanField(default=False, help_text="Manual kill switch."),
                ),
                ("block_reason", models.CharField(blank=True, max_length=255)),
                (
                    "enrichment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En curso"),
                            ("DONE", "Completado"),
                            ("FAILED", "Fallido"),
                            ("SKIPPED", "Omitido"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("enriched_at", models.DateTimeField(blank=True, null=True)),
                ("enrichment_model", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "indexes": [
                    models.Index(
                        fields=["enrichment_status", "keepa_fetched_at"],
                        name="product_enrich_fetched_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_blocked"], name="product_serveable_idx"
                    ),
                    models.Index(
                        fields=["-quality_score"], name="product_quality_desc_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("asin", "domain_id"), name="uniq_product_asin_domain"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "facet_type",
                    models.CharField(
                        choices=[
                            ("SYNTHETIC_QUERY", "Consulta sintética"),
                            ("GIFT_ANGLE", "Ángulo de regalo"),
                            ("SUMMARY", "Resumen"),
                        ],
                        default="SYNTHETIC_QUERY",
                        max_length=20,
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.halfvec.HalfVectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
                ("embedding_model", models.CharField(blank=True, max_length=64)),
                ("embedding_version", models.SmallIntegerField(default=1)),
                (
                    "occasions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facets",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "faceta de producto",
                "verbose_name_plural": "facetas de producto",
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="facet_embedding_hnsw",
                        opclasses=["halfvec_cosine_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "text", config="spanish"
                        ),
                        name="facet_text_fts_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["text"],
                        name="facet_text_trgm_idx",
                        opclasses=["gin_trgm_ops"],
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["occasions"], name="facet_occasions_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["recipients"], name="facet_recipients_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["interests"], name="facet_interests_idx"
                    ),
                ],
            },
        ),
    ]
