# Generated by Django 5.2.17 on 2026-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_cents",
            field=models.IntegerField(
                blank=True,
                help_text="Uso interno. Nunca se muestra al usuario.",
                null=True,
            ),
        ),
    ]
