# Generated by Django 5.2.17 on 2026-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_price_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="binding",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Keepa `binding`, p. ej. blu_ray.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_group",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Keepa `type`, p. ej. PHYSICAL_MOVIE.",
                max_length=255,
            ),
        ),
    ]
